INSERT INTO system_settings (key, value)
VALUES ('privacy_notice', '{
  "version":"2026-07-28.3",
  "effectiveDate":"July 28, 2026",
  "controllerName":"The school or institution that provides your Smartrack account and operates this deployment",
  "privacyContact":"Contact your school administrator or designated Data Protection Officer using the official contact details provided by your institution",
  "controllerInstruction":"The operating institution must give users its exact legal name, Data Protection Officer contact details, approved retention schedule, service providers, and any applicable cross-border processing details before production use.",
  "dataCategories":["Account and profile details, such as your name, email, phone number, course, school, role, and profile photo","OJT placement details, including assigned company, worksite, supervisor, schedule, and required hours","Attendance records, including time-in, time-out, credited hours, lateness, corrections, and completion progress","GPS coordinates, accuracy, capture time, and matched worksite during attendance actions and an active timed-in session","Time-in and time-out selfies, evidence notes, and files you choose or are required to submit","Documents, evaluations, requests, announcements, notification preferences, and related activity","Security and audit information, such as account actions, IP address, device or browser details, request identifiers, and error events"],
  "purposes":["Create and manage accounts, roles, OJT placements, schedules, and required hours","Verify attendance at approved worksites and provide students with attendance receipts","Calculate credited hours, lateness, completion progress, and attendance exceptions","Allow authorized coordinators and supervisors to review attendance, documents, evaluations, corrections, and completion requests","Detect inaccurate, duplicate, suspicious, or out-of-perimeter attendance and support human review","Protect accounts, investigate misuse, keep audit records and backups, and maintain service reliability","Create authorized student, school, and aggregate OJT reports"],
  "lawfulBasis":"The institution operating Smartrack is responsible for identifying and documenting the lawful basis for each purpose. Depending on the activity, this may be necessary to provide the educational or OJT service, comply with a legal obligation, protect a legitimate interest after proper assessment, or rely on specific consent where the law requires consent.",
  "consentExplanation":"Core OJT and attendance records may be required to provide the institution’s OJT service and may therefore rely on a basis other than consent. If the institution wants to use data for a new optional purpose that requires consent, it must ask separately using a specific, informed, freely given, and withdrawable choice. Refusing an optional consent must not be treated as refusing this notice.",
  "locationPurpose":"The app requests device location when you perform an attendance action. While you remain timed in, it may send updated coordinates to show your recent location to authorized personnel. The coordinates and accuracy are compared with approved worksites to verify attendance and flag exceptions. Tracking stops when the timed-in session ends; the app does not intentionally track you when you are timed out.",
  "selfiePurpose":"Time-in and time-out selfies are used as attendance evidence for review by authorized personnel. Smartrack stores the image but does not perform facial recognition or create a biometric face template.",
  "recipients":["You, for your own records and attendance receipts","Authorized administrators of the institution operating Smartrack","Your assigned coordinator and authorized school personnel","Your assigned company supervisor and authorized company personnel, limited to their responsibilities","Approved hosting, database, storage, email, and notification providers acting for the institution","Government, regulatory, or law-enforcement authorities only when disclosure is required or authorized by law"],
  "retention":"The institution must keep each category only for its documented, necessary period and then securely delete or anonymize it, unless a law, dispute, or audit requirement justifies longer retention. Ask the privacy contact for the exact schedule that applies to account, OJT, attendance, document, evaluation, audit, and backup records.",
  "imageRetentionDays":90,
  "automatedProcessing":"Smartrack automatically calculates distance from a worksite, lateness, credited hours, completion progress, anomalies, and risk indicators from configured rules. These results help authorized people prioritize review. They are not designed to make a final disciplinary, employment, or academic decision without human review. The app does not currently use facial recognition.",
  "security":"Smartrack uses role-based access, password hashing, multi-factor authentication for administrators, protected file access, HTTPS when correctly deployed, audit logs, request rate limits, database controls, validated uploads, and backups. Access is limited by assigned role, but the operating institution remains responsible for configuration, staff access, incident response, and provider oversight.",
  "rights":["Know whether and how your personal data is processed","Request access to your personal data and relevant processing information","Ask for inaccurate or incomplete data to be corrected","Object to processing when the right applies","Withdraw consent at any time for processing that is actually based on consent, without affecting earlier lawful processing","Request erasure, blocking, or suspension when legally applicable","Receive portable electronic data when the legal requirements apply","Seek compensation for damage caused by unlawful or improper processing","File a complaint with the Philippine National Privacy Commission"],
  "rightsProcess":"Contact the institution’s Data Protection Officer or privacy contact to exercise a right. The institution may need to verify your identity and may explain any lawful limitation that applies. You may also contact or file a complaint with the Philippine National Privacy Commission at privacy.gov.ph.",
  "declining":"You may sign out instead of acknowledging. The authenticated workspace will remain locked because the institution must show you this notice before you use it. Contact the institution’s administrator or Data Protection Officer to ask about the applicable legal basis, whether another attendance method is available, and what consequences—if any—apply if you do not use Smartrack.",
  "internationalProcessing":"Some approved technology providers may process or store data outside the Philippines, depending on the institution’s deployment. The institution must identify applicable providers and locations and ensure appropriate contractual, organizational, and technical safeguards.",
  "notConsent":"Selecting “Acknowledge and continue” records only that this notice was presented to you. It does not waive your privacy rights, authorize unrelated uses, or replace a separate consent where consent is legally required."
}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
