import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const _exportDTRtoPDFLegacy = (student, records, totalHours, requiredHours) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Smartrack OJT Monitoring System', pageWidth / 2, 15, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Daily Time Record (DTR)', pageWidth / 2, 25, { align: 'center' });

  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, pageWidth / 2, 33, { align: 'center' });

  // Student Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', 14, 52);

  doc.setDrawColor(37, 99, 235);
  doc.line(14, 54, pageWidth - 14, 54);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const info = [
    ['Name:', `${student.first_name || student.firstName} ${student.last_name || student.lastName}`],
    ['Email:', student.email || '—'],
    ['Course:', student.course || '—'],
    ['School:', student.school || '—'],
    ['Company:', student.company_name || student.companyName || '—'],
  ];

  let y = 62;
  info.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 55, y);
    y += 7;
  });

  // Progress
  const progress = Math.min((totalHours / requiredHours) * 100, 100).toFixed(1);
  y += 3;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('OJT Progress', 14, y);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Hours Rendered: ${totalHours}h`, 14, y);
  doc.text(`Required Hours: ${requiredHours}h`, 80, y);
  doc.text(`Completion: ${progress}%`, 150, y);
  y += 7;

  // Progress bar
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(200, 200, 200);
  doc.roundedRect(14, y, pageWidth - 28, 6, 2, 2, 'F');
  doc.setFillColor(37, 99, 235);
  const barWidth = ((parseFloat(progress) / 100) * (pageWidth - 28));
  if (barWidth > 0) doc.roundedRect(14, y, barWidth, 6, 2, 2, 'F');
  y += 15;

  // DTR Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Daily Time Records', 14, y);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 8;

  const tableData = records.map(r => [
    r.date ? new Date(r.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '—',
    r.clock_in ? new Date(r.clock_in).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : '—',
    r.clock_out ? new Date(r.clock_out).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : '—',
    r.total_hours ? `${r.total_hours}h` : '—',
    r.anomaly_flag ? 'Flagged' : 'Valid',
    r.evidence_note || '—',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Time In', 'Time Out', 'Hours', 'Status', 'Note']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 'auto' },
    },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    didParseCell: (data) => {
      if (data.column.index === 4 && data.section === 'body') {
        if (data.cell.text[0] === 'Flagged') {
          data.cell.styles.textColor = [220, 38, 38];
        } else {
          data.cell.styles.textColor = [22, 163, 74];
        }
      }
    },
  });

  // Footer
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('This document is system-generated by Smartrack OJT Monitoring System.', pageWidth / 2, finalY, { align: 'center' });
  doc.text(`Total Valid Hours: ${totalHours}h | Required: ${requiredHours}h | Completion: ${progress}%`, pageWidth / 2, finalY + 6, { align: 'center' });

  // Save
  const fileName = `DTR_${(student.first_name || student.firstName)}_${(student.last_name || student.lastName)}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

export const exportDTRtoPDF = (student, records, totalHours, requiredHours) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generatedAt = new Date();
  const renderedHours = Number(totalHours) || 0;
  const targetHours = Number(requiredHours) || 0;
  const progress = targetHours > 0
    ? Math.min((renderedHours / targetHours) * 100, 100).toFixed(1)
    : '0.0';
  const formatDate = value => value.toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
  });
  const recordDates = records
    .map(record => record.date)
    .filter(Boolean)
    .map(value => new Date(value))
    .filter(value => !Number.isNaN(value.getTime()))
    .sort((left, right) => left - right);
  const coveredPeriod = recordDates.length
    ? `${formatDate(recordDates[0])} to ${formatDate(recordDates[recordDates.length - 1])}`
    : 'No attendance dates';
  const uniquePart = globalThis.crypto?.randomUUID?.().split('-')[0]
    || Math.random().toString(36).slice(2, 10);
  const reference = `ST-DTR-${generatedAt.toISOString().slice(0, 10).replaceAll('-', '')}-${uniquePart.toUpperCase()}`;
  const needsReview = records.some(record => (
    record.anomaly_flag || record.is_valid === false || (record.clock_in && !record.clock_out)
  ));

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('Smartrack OJT Monitoring System', pageWidth / 2, 15, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text('Student Daily Time Record (DTR)', pageWidth / 2, 25, { align: 'center' });
  doc.setFontSize(9);
  doc.text(`Generated: ${generatedAt.toLocaleString('en-US')}`, pageWidth / 2, 33, { align: 'center' });

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Report Information', 14, 51);
  doc.setDrawColor(37, 99, 235);
  doc.line(14, 54, pageWidth - 14, 54);

  const info = [
    ['Student name:', `${student.first_name || student.firstName || ''} ${student.last_name || student.lastName || ''}`.trim() || '-'],
    ['Student ID:', student.id || '-'],
    ['Institution:', student.school || '-'],
    ['Course / program:', student.course || '-'],
    ['Training company:', student.company_name || student.companyName || '-'],
    ['Covered period:', coveredPeriod],
    ['Report reference:', reference],
  ];
  let y = 62;
  doc.setFontSize(9);
  info.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), 53, y, { maxWidth: pageWidth - 67 });
    y += 6;
  });

  y += 3;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Attendance Summary', 14, y);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 9;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Credited hours: ${renderedHours}h`, 14, y);
  doc.text(`Required hours: ${targetHours}h`, 77, y);
  doc.text(`Completion: ${progress}%`, 145, y);
  y += 8;

  const tableData = records.map(record => [
    record.date ? formatDate(new Date(record.date)) : '-',
    record.clock_in
      ? new Date(record.clock_in).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
      : '-',
    record.clock_out
      ? new Date(record.clock_out).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
      : '-',
    record.total_hours ? `${record.total_hours}h` : '-',
    record.anomaly_flag || record.is_valid === false || (record.clock_in && !record.clock_out)
      ? 'Review'
      : 'Recorded',
    record.evidence_note || '-',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Time In', 'Time Out', 'Hours', 'Status', 'Note']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 23 },
      2: { cellWidth: 23 },
      3: { cellWidth: 18 },
      4: { cellWidth: 22 },
      5: { cellWidth: 'auto' },
    },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    didParseCell: (data) => {
      if (data.column.index === 4 && data.section === 'body') {
        data.cell.styles.textColor = data.cell.text[0] === 'Review'
          ? [220, 38, 38]
          : [22, 163, 74];
      }
    },
  });

  let footerY = doc.lastAutoTable.finalY + 10;
  if (footerY > pageHeight - 35) {
    doc.addPage();
    footerY = 20;
  }
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('STUDENT-GENERATED COPY - NOT AN OFFICIAL CERTIFIED RECORD', pageWidth / 2, footerY, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.text(
    needsReview
      ? 'Status: This export contains entries requiring review by authorized personnel.'
      : 'Status: No flagged entries appear here; certification by authorized personnel is still required.',
    pageWidth / 2,
    footerY + 6,
    { align: 'center', maxWidth: pageWidth - 28 },
  );
  doc.text(`Reference: ${reference}`, pageWidth / 2, footerY + 12, { align: 'center' });
  doc.text(
    `Credited: ${renderedHours}h | Required: ${targetHours}h | Completion: ${progress}%`,
    pageWidth / 2,
    footerY + 18,
    { align: 'center' },
  );

  const firstName = student.first_name || student.firstName || 'Student';
  const lastName = student.last_name || student.lastName || '';
  doc.save(`DTR_${firstName}_${lastName}_${generatedAt.toISOString().split('T')[0]}.pdf`);
};

export const exportEvaluationToPDF = (student, evaluations) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Smartrack OJT Monitoring System', pageWidth / 2, 15, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Student Evaluation Report', pageWidth / 2, 25, { align: 'center' });

  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, pageWidth / 2, 33, { align: 'center' });

  // Student Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', 14, 52);
  doc.setDrawColor(37, 99, 235);
  doc.line(14, 54, pageWidth - 14, 54);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const info = [
    ['Name:', `${student.first_name} ${student.last_name}`],
    ['Email:', student.email || '—'],
    ['Course:', student.course || '—'],
    ['School:', student.school || '—'],
    ['Company:', student.company_name || '—'],
  ];

  let y = 62;
  info.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 55, y);
    y += 7;
  });

  // Evaluations
  y += 5;
  evaluations.forEach(ev => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`${ev.period.toUpperCase()} EVALUATION`, 14, y);
    doc.line(14, y + 2, pageWidth - 14, y + 2);
    y += 10;

    const scores = typeof ev.scores === 'string' ? JSON.parse(ev.scores) : ev.scores;
    const scoreRows = Object.entries(scores).map(([key, value]) => [
      key.charAt(0).toUpperCase() + key.slice(1),
      `${value}/100`,
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Criteria', 'Score']],
      body: [
        ...scoreRows,
        ['OVERALL SCORE', `${ev.total_score}/100`],
      ],
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      columnStyles: { 0: { cellWidth: 120 }, 1: { cellWidth: 50 } },
      didParseCell: (data) => {
        if (data.row.index === scoreRows.length && data.section === 'body') {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [37, 99, 235];
          data.cell.styles.textColor = 255;
        }
      },
    });

    y = doc.lastAutoTable.finalY + 8;

    if (ev.comments) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.text(`Comments: ${ev.comments}`, 14, y);
      y += 8;
    }

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Submitted by: ${ev.supervisor_first} ${ev.supervisor_last} | ${new Date(ev.submitted_at).toLocaleDateString()}`, 14, y);
    doc.setTextColor(0, 0, 0);
    y += 12;
  });

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('This document is system-generated by Smartrack OJT Monitoring System.', pageWidth / 2, y + 5, { align: 'center' });

  const fileName = `Evaluation_${student.first_name}_${student.last_name}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

/**
 * Export DTR records as CSV for large datasets
 * @param {object} student - Student object
 * @param {array} records - Daily time records
 * @param {number} totalHours - Total hours rendered
 * @param {number} requiredHours - Required hours
 * @returns {string} CSV formatted content
 */
export const exportDTRtoCSV = (student, records, totalHours, requiredHours) => {
  const headers = ['Date', 'Time In', 'Time Out', 'Total Hours', 'Status', 'Evidence Note', 'Created By', 'Created At'];

  // Student summary header
  const summaryLines = [
    ['Smartrack OJT Monitoring System - Daily Time Record Export'],
    [''],
    ['Student Information'],
    ['Name', `${student.first_name || student.firstName} ${student.last_name || student.lastName}`],
    ['Email', student.email || ''],
    ['Course', student.course || ''],
    ['School', student.school || ''],
    ['Company', student.company_name || student.companyName || ''],
    [''],
    ['OJT Progress'],
    ['Hours Rendered', totalHours],
    ['Required Hours', requiredHours],
    ['Completion %', Math.min((totalHours / requiredHours) * 100, 100).toFixed(1)],
    [''],
    [...headers],
  ];

  // Add records
  const dataLines = records.map(r => [
    r.date ? new Date(r.date).toLocaleDateString('en-US') : '',
    r.clock_in ? new Date(r.clock_in).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : '',
    r.clock_out ? new Date(r.clock_out).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : '',
    r.total_hours || '',
    r.anomaly_flag ? 'Flagged' : 'Valid',
    r.evidence_note || '',
    r.created_by || '',
    r.created_at ? new Date(r.created_at).toLocaleString('en-US') : '',
  ]);

  // Convert all rows to CSV
  const escapeCSV = (value) => {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const csvContent = [...summaryLines, ...dataLines]
    .map(row => row.map(escapeCSV).join(','))
    .join('\n');

  return csvContent;
};

/**
 * Export evaluation records as CSV
 * @param {object} student - Student object
 * @param {array} evaluations - Evaluation records
 * @returns {string} CSV formatted content
 */
export const exportEvaluationToCSV = (student, evaluations) => {
  const headers = ['Period', 'Criteria', 'Score', 'Overall Score', 'Supervisor', 'Submitted Date', 'Comments'];

  const summaryLines = [
    ['Smartrack OJT Monitoring System - Evaluation Report'],
    [''],
    ['Student Information'],
    ['Name', `${student.first_name} ${student.last_name}`],
    ['Email', student.email || ''],
    ['Course', student.course || ''],
    ['School', student.school || ''],
    ['Company', student.company_name || ''],
    [''],
    [...headers],
  ];

  const escapeCSV = (value) => {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const dataLines = [];
  evaluations.forEach(ev => {
    const scores = typeof ev.scores === 'string' ? JSON.parse(ev.scores) : ev.scores || {};
    const criteriaEntries = Object.entries(scores);

    criteriaEntries.forEach((entry, index) => {
      dataLines.push([
        index === 0 ? ev.period.toUpperCase() : '',
        entry[0],
        `${entry[1]}/100`,
        index === criteriaEntries.length - 1 ? `${ev.total_score}/100` : '',
        index === 0 ? `${ev.supervisor_first} ${ev.supervisor_last}` : '',
        index === 0 ? new Date(ev.submitted_at).toLocaleDateString() : '',
        index === criteriaEntries.length - 1 ? (ev.comments || '') : '',
      ]);
    });
  });

  const csvContent = [...summaryLines, ...dataLines]
    .map(row => row.map(escapeCSV).join(','))
    .join('\n');

  return csvContent;
};

/**
 * Download CSV content as file
 * @param {string} csvContent - CSV formatted content
 * @param {string} filename - File name without extension
 */
export const downloadCSVFile = (csvContent, filename = 'export') => {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
