import { useState, useEffect, useCallback } from 'react';
import { getOverviewAnalytics, getStudentAnalytics } from '../../api/analytics';
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart,
  ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts';
import VectorIcon from '../../components/common/VectorIcon';
import SkeletonPage from '../../components/common/Skeleton';
import CollapsibleSection from '../../components/common/CollapsibleSection';
import StudentTypeahead from '../../components/common/StudentTypeahead';

const formatWeek = (value) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, {
  month: 'short', day: 'numeric',
});

const scoreColor = (score) => score >= 80 ? 'var(--success)' : score >= 60 ? 'var(--warning)' : 'var(--danger)';
const confidenceBadge = level => level === 'High' ? 'badge-success' : level === 'Medium' ? 'badge-warning' : 'badge-danger';

const AccurateTooltip = ({ active, payload, label, type }) => {
  if (!active || !payload?.length) return null;
  const point = payload[0]?.payload || {};
  const rows = type === 'attendance'
    ? [['Expected days', point.expectedDays], ['Scheduled present', point.scheduledPresentDays], ['Additional verified', point.additionalVerifiedDays], ['Absent', point.absentDays], ['Late', point.lateDays], ['Rate', point.attendanceRate == null ? '—' : `${point.attendanceRate}%`]]
    : type === 'hours'
      ? [['Verified', `${point.cumulativeHours}h`], ['Planned', point.plannedHours == null ? '—' : `${point.plannedHours}h`], ['Completed', `${point.hoursProgress}%`]]
      : type === 'documents'
        ? [['Submitted', `${point.documentsSubmitted}/${point.totalDocuments}`], ['Approved', `${point.documentsApproved}/${point.totalDocuments}`]]
        : type === 'prediction'
          ? [['Actual', point.actualScore == null ? '—' : `${point.actualScore}/100`], ['Projected', point.predictedScore == null ? '—' : `${point.predictedScore}/100`]]
          : [['Score', point.evaluationScore == null ? '—' : `${point.evaluationScore}/100`]];
  return (
    <div className="chart-tooltip">
      <div className="chart-tooltip-title">Week of {formatWeek(label)}</div>
      {rows.map(([name, value]) => (
        <div key={name} className="chart-tooltip-row"><span>{name}</span><strong>{value}</strong></div>
      ))}
    </div>
  );
};

const CHART_TABS = [
  { key: 'forecast', label: 'Forecast' },
  { key: 'attendance', label: 'Attendance' },
  { key: 'hours', label: 'Hours' },
  { key: 'documents', label: 'Documents' },
  { key: 'evaluation', label: 'Evaluations' },
];

const axisTick = { fontSize: 11, fill: 'var(--text-3)' };
const legendStyle = { fontSize: '12px', paddingTop: '8px' };

const formatAnalysis = (text) => {
  if (!text) return null;
  const normalized = String(text).replace(/\r\n/g, '\n').trim();
  const sections = normalized.split(/\n(?=(?:\d+\.\s*)?(?:\*{1,2}|#{1,3}\s+)?[A-Z][A-Z /&-]{3,})/).filter(Boolean);
  return sections.map((section, i) => {
    const lines = section.trim().split('\n');
    const rawTitle = lines[0].replace(/^\d+\.\s*/, '').replace(/^#{1,3}\s*/, '').replace(/\*/g, '').trim();
    const content = lines.slice(1).join('\n').trim();
    const looksLikeHeading = rawTitle.length < 72 && /[A-Z]/.test(rawTitle);
    const title = content || looksLikeHeading ? rawTitle : 'Summary';
    const body = content || (title === 'Summary' ? rawTitle : '');
    const isRating = /RATING|SUMMARY|COHORT SUMMARY/i.test(title);
    const isBad = /At Risk|Needs Improvement|Needs Intervention/i.test(`${title}\n${body}`);
    const isGood = /Excellent|Very Good|Good/i.test(body) && !isBad;
    const tone = isRating ? (isBad ? 'is-bad' : isGood ? 'is-good' : 'is-info') : '';
    return (
      <div key={`${title}-${i}`} className={`analysis-section ${tone}`.trim()}>
        <div className="analysis-section-title">{title}</div>
        {body && <div className="analysis-section-body">{body}</div>}
      </div>
    );
  });
};

const SourceBadge = ({ source }) => (
  <span className={`badge ${source === 'claude' ? 'badge-primary' : 'badge-gray'}`} title={source === 'claude' ? 'Generated by Claude from live records' : 'Generated locally from live records'}>
    {source === 'claude' ? 'AI' : 'Auto'}
  </span>
);

const StudentChart = ({ tab, data }) => {
  const trend = data.stats.weeklyTrend;
  if (tab === 'forecast') {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <LineChart data={data.prediction.forecast} margin={{ top: 8, right: 8, left: -16, bottom: 8 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
          <XAxis dataKey="week" tickFormatter={formatWeek} tick={axisTick} />
          <YAxis domain={[0, 100]} tick={axisTick} />
          <Tooltip content={<AccurateTooltip type="prediction" />} />
          <Legend wrapperStyle={legendStyle} />
          <ReferenceLine y={75} stroke="#CBD5E1" strokeDasharray="4 4" />
          <Line type="linear" dataKey="actualScore" name="Actual" stroke="#2563EB" strokeWidth={3} dot={{ r: 4 }} connectNulls={false} />
          <Line type="linear" dataKey="predictedScore" name="Projected" stroke="#7C3AED" strokeWidth={3} strokeDasharray="7 5" dot={{ r: 4, fill: '#7C3AED' }} connectNulls />
        </LineChart>
      </ResponsiveContainer>
    );
  }
  if (!trend.length) return <div className="analytics-chart-empty">No trend data yet.</div>;
  if (tab === 'attendance') {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <BarChart data={trend} margin={{ top: 8, right: 8, left: -22, bottom: 8 }} barCategoryGap="24%">
          <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
          <XAxis dataKey="week" tickFormatter={formatWeek} tick={axisTick} />
          <YAxis allowDecimals={false} tick={axisTick} />
          <Tooltip content={<AccurateTooltip type="attendance" />} cursor={{ fill: 'rgba(37,99,235,0.06)' }} />
          <Legend wrapperStyle={legendStyle} />
          <Bar dataKey="scheduledPresentDays" name="Present" stackId="attendance" fill="#2563EB" radius={[6, 6, 0, 0]} />
          <Bar dataKey="additionalVerifiedDays" name="Extra" stackId="attendance" fill="#10B981" radius={[6, 6, 0, 0]} />
          <Bar dataKey="absentDays" name="Absent" stackId="attendance" fill="#F97316" radius={[6, 6, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    );
  }
  if (tab === 'hours') {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <AreaChart data={trend} margin={{ top: 8, right: 8, left: -12, bottom: 8 }}>
          <defs>
            <linearGradient id="verifiedHoursFill" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%" stopColor="#059669" stopOpacity={0.32} />
              <stop offset="95%" stopColor="#059669" stopOpacity={0.02} />
            </linearGradient>
          </defs>
          <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
          <XAxis dataKey="week" tickFormatter={formatWeek} tick={axisTick} />
          <YAxis tick={axisTick} unit="h" />
          <Tooltip content={<AccurateTooltip type="hours" />} />
          <Legend wrapperStyle={legendStyle} />
          <ReferenceLine y={Number(data.student.required_hours)} stroke="#64748B" strokeDasharray="5 5" label={{ value: 'Required', position: 'insideTopRight', fill: '#64748B', fontSize: 11 }} />
          <Area type="monotone" dataKey="cumulativeHours" name="Verified" stroke="#059669" strokeWidth={3} fill="url(#verifiedHoursFill)" dot={{ r: 3, fill: '#059669' }} />
          <Line type="linear" dataKey="plannedHours" name="Planned" stroke="#94A3B8" strokeWidth={2} strokeDasharray="6 4" dot={false} connectNulls />
        </AreaChart>
      </ResponsiveContainer>
    );
  }
  if (tab === 'documents') {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <LineChart data={trend} margin={{ top: 8, right: 8, left: -22, bottom: 8 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
          <XAxis dataKey="week" tickFormatter={formatWeek} tick={axisTick} />
          <YAxis allowDecimals={false} domain={[0, Math.max(1, data.stats.totalDocs)]} tick={axisTick} />
          <Tooltip content={<AccurateTooltip type="documents" />} />
          <Legend wrapperStyle={legendStyle} />
          <ReferenceLine y={data.stats.totalDocs} stroke="#94A3B8" strokeDasharray="5 5" />
          <Line type="stepAfter" dataKey="documentsSubmitted" name="Submitted" stroke="#D97706" strokeWidth={3} dot={{ r: 3 }} />
          <Line type="stepAfter" dataKey="documentsApproved" name="Approved" stroke="#0EA5E9" strokeWidth={3} dot={{ r: 3 }} />
        </LineChart>
      </ResponsiveContainer>
    );
  }
  return (
    <ResponsiveContainer width="100%" height="100%">
      <LineChart data={trend} margin={{ top: 8, right: 12, left: -16, bottom: 8 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
        <XAxis dataKey="week" tickFormatter={formatWeek} tick={axisTick} />
        <YAxis domain={[0, 100]} tick={axisTick} />
        <Tooltip content={<AccurateTooltip type="evaluation" />} />
        <ReferenceLine y={75} stroke="#CBD5E1" strokeDasharray="4 4" />
        <Line type="linear" dataKey="evaluationScore" name="Evaluation" stroke="#7C3AED" strokeWidth={3} dot={{ r: 6, fill: '#7C3AED', stroke: '#fff', strokeWidth: 2 }} activeDot={{ r: 8 }} connectNulls />
      </LineChart>
    </ResponsiveContainer>
  );
};

const AnalyticsPage = ({ students, onOpenStudents, onOpenProgress, onOpenRisks }) => {
  const [view, setView] = useState('overview');
  const [overviewData, setOverviewData] = useState(null);
  const [studentData, setStudentData] = useState(null);
  const [selectedStudent, setSelectedStudent] = useState('');
  const [studentSearch, setStudentSearch] = useState('');
  const [chartTab, setChartTab] = useState('forecast');
  const [loading, setLoading] = useState(false);
  const [toast, setToast] = useState('');

  const showToast = useCallback((msg) => { setToast(msg); setTimeout(() => setToast(''), 6000); }, []);

  const fetchOverview = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getOverviewAnalytics();
      setOverviewData(res.data);
    } catch (error) {
      showToast(error.response?.data?.message || 'Could not reach the analytics service. Please try again.');
    }
    finally { setLoading(false); }
  }, [showToast]);

  const fetchStudentAnalytics = async (id) => {
    if (!id) return;
    setLoading(true);
    setStudentData(null);
    try {
      const res = await getStudentAnalytics(id);
      setStudentData(res.data);
      setChartTab('forecast');
    } catch (error) {
      showToast(error.response?.data?.message || 'Could not reach the analytics service. Please try again.');
    }
    finally { setLoading(false); }
  };

  useEffect(() => {
    if (view === 'overview') fetchOverview();
  }, [view, fetchOverview]);

  const analyzableStudents = (students || []).filter(student => student.deployment_id);
  const attendance = studentData?.stats.attendance;

  return (
    <div>
      <div className="analytics-view-toggle" role="tablist" aria-label="Analytics scope">
        <button type="button" role="tab" aria-selected={view === 'overview'} className={view === 'overview' ? 'is-active' : ''} onClick={() => setView('overview')}>Cohort</button>
        <button type="button" role="tab" aria-selected={view === 'student'} className={view === 'student' ? 'is-active' : ''} onClick={() => setView('student')}>Student</button>
      </div>

      {view === 'overview' && (
        loading ? (
          <SkeletonPage variant="dashboard" label="Analyzing cohort" />
        ) : overviewData ? (
          <div className="card analytics-report-card">
            <div className="analytics-report-head">
              <span className="analytics-report-icon"><VectorIcon name="bot" size={18} /></span>
              <strong>Cohort report</strong>
              <SourceBadge source={overviewData.analysisSource} />
              <button type="button" className="action-btn action-btn-gray icon-label analytics-report-refresh" onClick={fetchOverview}>
                <VectorIcon name="refresh" size={15} /> Refresh
              </button>
            </div>
            <div className="analytics-quick-stats">
              <button type="button" onClick={onOpenStudents}><b>{overviewData.stats.totalStudents}</b> students</button>
              <button type="button" onClick={onOpenProgress || onOpenStudents}><b>{overviewData.stats.avgProgress}%</b> avg progress</button>
              <button type="button" className="is-danger" onClick={onOpenRisks}><b>{overviewData.stats.atRisk}</b> at risk</button>
            </div>
            {formatAnalysis(overviewData.analysis)}
          </div>
        ) : (
          <div className="card analytics-empty">
            <button type="button" onClick={fetchOverview} className="btn-primary">Generate report</button>
          </div>
        )
      )}

      {view === 'student' && (
        <>
          <div className="card analytics-student-picker">
            <div className="analytics-student-controls">
              <StudentTypeahead
                id="analytics-find-student"
                students={analyzableStudents}
                value={studentSearch}
                onChange={(next) => {
                  setStudentSearch(next);
                  if (!next) {
                    setSelectedStudent('');
                    setStudentData(null);
                  }
                }}
                onSelect={(student) => {
                  setStudentSearch(`${student.first_name || ''} ${student.last_name || ''}`.trim());
                  setSelectedStudent(student.id);
                  setStudentData(null);
                }}
                label="Student"
                placeholder="Search deployed students"
              />
              <button onClick={() => fetchStudentAnalytics(selectedStudent)}
                disabled={!selectedStudent || loading || !analyzableStudents.length}
                type="button"
                className="btn-primary analytics-student-analyze">
                {loading ? 'Analyzing…' : 'Analyze'}
              </button>
            </div>
          </div>

          {loading ? (
            <SkeletonPage variant="dashboard" label="Analyzing student" />
          ) : studentData ? (
            <>
              <div className="card analytics-score-card">
                <div className="analytics-score-head">
                  <div>
                    <strong>{studentData.student.first_name} {studentData.student.last_name}</strong>
                    <span className="coordinator-muted">{studentData.performance.rating}</span>
                  </div>
                  <div className="analytics-score-value" style={{ color: scoreColor(studentData.performance.score) }}>
                    {studentData.performance.score}<small>/100</small>
                  </div>
                </div>
                <div className="analytics-mini-stats">
                  <div><b>{studentData.stats.totalHours}h</b><span>Hours</span></div>
                  <div><b style={{ color: scoreColor(attendance.attendanceRate) }}>{attendance.attendanceRate}%</b><span>Attendance</span></div>
                  <div><b>{attendance.punctualityRate}%</b><span>On time</span></div>
                  <div><b className={studentData.stats.anomalyDays ? 'coordinator-danger-text' : ''}>{studentData.stats.anomalyDays}</b><span>Flags</span></div>
                </div>
                <div className="analytics-breakdown">
                  {studentData.performance.components.map(component => (
                    <div key={component.key} className={`analytics-breakdown-row${component.available ? '' : ' is-unavailable'}`}>
                      <span>{component.label}</span>
                      <div className="analytics-breakdown-bar">
                        <div style={{ width: `${component.available ? component.score : 0}%`, background: scoreColor(component.score) }} />
                      </div>
                      <strong>{component.available ? `${Math.round(component.score)}%` : '—'}</strong>
                    </div>
                  ))}
                </div>
              </div>

              <div className="card analytics-chart-card">
                <div className="analytics-chart-tabs" role="tablist" aria-label="Charts">
                  {CHART_TABS.map(tab => (
                    <button key={tab.key} type="button" role="tab" aria-selected={chartTab === tab.key} className={chartTab === tab.key ? 'is-active' : ''} onClick={() => setChartTab(tab.key)}>
                      {tab.label}
                    </button>
                  ))}
                </div>
                {chartTab === 'forecast' && (
                  <div className="analytics-forecast-meta">
                    <span><b>{studentData.prediction.projectedScore}</b>/100 projected</span>
                    <span>{studentData.prediction.direction}</span>
                    <span>{studentData.prediction.weeklyChange > 0 ? '+' : ''}{studentData.prediction.weeklyChange}/wk</span>
                    <span className={`badge ${confidenceBadge(studentData.prediction.confidence)}`}>{studentData.prediction.confidence} confidence</span>
                  </div>
                )}
                <div className="analytics-chart-area">
                  <StudentChart tab={chartTab} data={studentData} />
                </div>
              </div>

              <CollapsibleSection title="Full report" className="analytics-report-collapse">
                <div className="analytics-report-meta"><SourceBadge source={studentData.analysisSource} /></div>
                {studentData.prediction.narrative && <p className="analytics-narrative">{studentData.prediction.narrative}</p>}
                {studentData.weeklyNarrative && <p className="analytics-narrative">{studentData.weeklyNarrative}</p>}
                {formatAnalysis(studentData.analysis)}
              </CollapsibleSection>
            </>
          ) : selectedStudent ? (
            <div className="card analytics-empty">Click <strong>Analyze</strong> to generate the report.</div>
          ) : null}
        </>
      )}

      {toast && <div className="toast toast-error">{toast}</div>}
    </div>
  );
};

export default AnalyticsPage;
